# Generated by Django 5.1 on 2024-09-10 14:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('razao_social', models.CharField(max_length=255)),
                ('nome_fantasia', models.CharField(blank=True, max_length=255)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('is_estadual', models.CharField(blank=True, max_length=18)),
                ('is_municipal', models.CharField(blank=True, max_length=18)),
                ('logradouro', models.CharField(blank=True, max_length=255)),
                ('estado', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2)),
                ('telefone', models.CharField(max_length=50)),
                ('email_empresa', models.EmailField(max_length=255)),
                ('observacao', models.CharField(max_length=255)),
                ('prefixo', models.CharField(blank=True, default='', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(related_name='user_set', related_query_name='user', to='auth.group')),
                ('user_permissions', models.ManyToManyField(related_name='user_set', related_query_name='user', to='auth.permission')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contact.empresa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_ordem', models.CharField(editable=False, max_length=20, unique=True)),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('tipo_manutencao', models.CharField(choices=[('preventiva', 'preventiva'), ('eletrica', 'Manutenção Elétrica'), ('hidraulica', 'Manutenção Hidráulica')], max_length=255)),
                ('localizacao_atv', models.CharField(choices=[('interno', 'Interno'), ('externo', 'Externo')], max_length=255)),
                ('prioridade_chamado', models.CharField(choices=[('Alta', 'Alta Prioridade'), ('Normal', 'Prioridade Normal'), ('Baixa', 'Baixa Prioridade')], max_length=255)),
                ('local_especifico', models.CharField(max_length=255)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('empresa_nome_fantasia', models.CharField(blank=True, max_length=255)),
                ('empresa_cnpj', models.CharField(blank=True, max_length=18)),
                ('usuario_telefone', models.CharField(blank=True, max_length=50)),
                ('data_inicio_atv', models.DateTimeField(blank=True, null=True)),
                ('data_fim_atv', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImagemChamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ordem', models.CharField(max_length=20)),
                ('tipo_imagem', models.CharField(choices=[('antes', 'Antes'), ('depois', 'Depois')], max_length=50)),
                ('imagem_cliente_operador', models.ImageField(upload_to='fotos_Abertura/%Y/%m/%d')),
                ('imagem_prestador', models.ImageField(blank=True, null=True, upload_to='fotos_fechamento/%Y/%m/%d/')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='contact.chamado')),
            ],
        ),
    ]
