# Generated by Django 5.1 on 2024-09-16 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_usuario_tipo_usuario_alter_usuario_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_criados', to=settings.AUTH_USER_MODEL),
        ),
    ]
