# Generated by Django 5.1 on 2024-09-19 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_tarefa_chamado_area_chamado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chamados', to='contact.empresa'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='prestadora_servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empresa', to='contact.empresa'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='tecnico_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tecnicos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='area_chamado',
            field=models.CharField(choices=[('Eletrica', 'Elétrica'), ('Hidraulica', 'Hidráulica'), ('Civil', 'Civil')], default='Não especificado', max_length=255),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='tipo_manutencao',
            field=models.CharField(choices=[('preventiva', 'Preventiva'), ('emergial', 'Emergial'), ('corretiva', 'Corretiva')], max_length=255),
        ),
    ]
