# Generated by Django 5.1 on 2024-09-20 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_area_alter_chamado_area_chamado_alter_tarefa_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='nome',
            field=models.CharField(max_length=255),
        ),
    ]
