# Generated by Django 5.1 on 2024-09-20 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0011_remove_chamado_usuario_telefone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chamado',
            name='usuario',
        ),
    ]
