# Generated by Django 5.1 on 2024-09-25 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0015_detalhetarefa'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalheTarefaPreenchido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotos_clientes', models.ImageField(blank=True, null=True, upload_to='fotos_clientes/')),
                ('fotos_ajustes', models.ImageField(blank=True, null=True, upload_to='fotos_ajustes/')),
                ('observacao', models.TextField(blank=True, null=True)),
                ('concluido', models.BooleanField(default=False)),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.chamado')),
                ('detalhe_tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.detalhetarefa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ImagemChamado',
        ),
    ]
