# Generated by Django 5.1 on 2024-10-02 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0017_alter_chamado_tarefa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='imagens_tarefas/')),
                ('detalhe_tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='contact.detalhetarefapreenchido')),
                ('numero_ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.chamado')),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.tarefa')),
            ],
        ),
    ]
