# Generated by Django 5.1 on 2024-10-02 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0018_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagem',
            name='tipo_imagem',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('ajuste', 'Ajuste')], default='cliente', max_length=10),
        ),
    ]
