# Generated by Django 5.1 on 2024-10-04 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0020_chamado_status_chamado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chamado',
            old_name='status_Chamado',
            new_name='status_chamado',
        ),
    ]
