# Generated by Django 5.1 on 2024-10-09 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0021_rename_status_chamado_chamado_status_chamado'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contact.empresa'),
        ),
        migrations.AlterField(
            model_name='area',
            name='nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='area',
            constraint=models.UniqueConstraint(fields=('nome', 'empresa'), name='unique_area_per_empresa'),
        ),
    ]
