# Generated by Django 5.1 on 2024-10-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0022_area_empresa_alter_area_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('admin', 'Administrador'), ('operador', 'Operador'), ('manager', 'Cliente'), ('user', 'Terceiro')], default='user', max_length=10),
        ),
    ]
