# Generated by Django 5.1 on 2024-10-29 18:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0025_imagemchamado'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemchamado',
            name='data_upload',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='imagemchamado',
            name='chamado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='contact.chamado'),
        ),
        migrations.AlterField(
            model_name='imagemchamado',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_chamados/'),
        ),
    ]
