# Generated by Django 5.1 on 2024-11-01 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0028_chamado_assinatura_chamado_email_assinante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='data_fim_chamado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='status_chamado',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('concluido', 'Concluído'), ('executando', 'Executando'), ('rejeitado', 'Rejeitado'), ('assinatura', 'Aguardando assinatura')], default='aberto', max_length=255),
        ),
    ]
