# Generated by Django 5.1 on 2024-11-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0029_chamado_data_fim_chamado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='cargo_assinante',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
