# Generated by Django 5.1 on 2024-11-21 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0030_chamado_cargo_assinante'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagemchat',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contact.empresa'),
        ),
    ]
