# Generated by Django 5.1 on 2024-11-22 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0031_mensagemchat_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='data_limite_atendimento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TempoManutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_manutencao', models.CharField(choices=[('preventiva', 'Preventiva'), ('emergial', 'Emergial'), ('corretiva', 'Corretiva')], max_length=255)),
                ('tempo', models.DurationField(help_text='Tempo em dias, horas, etc.')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tempos_manutencao', to='contact.empresa')),
            ],
        ),
    ]
