# Generated by Django 5.1.4 on 2025-01-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0034_chamado_assinatura_tecnico_chamado_nome_tecnico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='email_responsavel',
            field=models.EmailField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='empresa',
            name='responsavel_empre',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='tipo_manutencao',
            field=models.CharField(choices=[('preventiva', 'Preventiva'), ('emergencial', 'Emergencial'), ('corretiva', 'Corretiva')], max_length=255),
        ),
    ]
