# Generated by Django 5.1.4 on 2025-01-23 14:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0037_empresa_analista_resp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chamado',
            name='tecnico_responsavel',
        ),
        migrations.AddField(
            model_name='chamado',
            name='tecnicos_responsaveis',
            field=models.ManyToManyField(blank=True, related_name='chamados_tecnicos', to=settings.AUTH_USER_MODEL),
        ),
    ]
